Fix a typo in an example in NumPy for images
An example in A crash course on NumPy for images suggests that the
watershed function is a part of the morphology module instead of the
segmentation module. As is, running the example raises an attribute
error: module 'skimage.morphology' has no attribute 'watershed'.