Bypass test failure due to "unclosed file" with pytest.warn (#6931)
Patches a test failure that started showing up just before a v0.21 release (candidate). 

The failing unit test

FAILED io/tests/test_imageio.py::TestSave::test_bool_array_save - ValueError: Unexpected warning: unclosed file <_io.BufferedReader name='/home/runner/.cache/scikit-image/main/data/no_time_for_that_tiny.gif'>