Try libomp install via conda without sudo
Maybe that's the reason the "Post Setup Conda" step fails with
```
Error: EACCES: permission denied, rename '/Users/runner/conda_pkgs_dir/llvm-openmp-11.1.0-hda6cdc1_1' -> '/var/folders/p1/44pzfl0j2m301zzfb0fv0p380000gn/T/llvm-openmp-11.1.0-hda6cdc1_1'
```